"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schema for my building block'
type: object
definitions:
  test:
    type: string
properties:
  a:
    type: string
    format: uri
  b:
    type: number
  c:
    $ref: bblocks://avillar.sandbox.my-building-block#/definitions/test
required:
  - a
  - b
